mensaje = "hola"
mensaje+= " "
mensaje+= "soy"
mensaje+= " "
mensaje+= "messi"
mensaje+= "  "
mensaje+= "el"
mensaje+= "  "
mensaje+= "mejor"
mensaje+= "  "
mensaje+= "del"
mensaje+= " "
mensaje+= "mundo"
print(mensaje)